# Generated by Django 6.0.5 on 2026-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='error_message',
        ),
        migrations.AddField(
            model_name='job',
            name='error_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='job',
            name='latest_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
